Repository PanZezhong1725/operators, pull requests merged in 2024-08, with the labels that each got.

#33 Refactor：算子库重构
  README.md
  include/data_type.h
  include/device.h
  include/handle.h
  include/handle/handle_export.h
  include/operators.h
  include/ops/causal_softmax/causal_softmax.h
  include/ops/matmul/matmul.h
  include/ops/rearrage/rearrange.h
  include/ops/reform/reform.h
  include/ops/rms_norm/rms_norm.h
  include/ops/rotary_embedding/rotary_embedding.h
  include/ops/swiglu/swiglu.h
  include/status.h
  include/tensor.h
  include/tensor/tensor_descriptor.h
  operatorspy/__init__.py
  operatorspy/liboperators.py
  operatorspy/tests/causal_softmax.py
  operatorspy/utils.py
  src/devices/bang/bang_handle.cc
  src/devices/bang/bang_handle.h
  src/devices/bang/common_bang.h
  src/devices/bang/handle_pool.cc
  src/devices/bang/handle_pool.h
  src/devices/cpu/cpu_handle.cc
  src/devices/cpu/cpu_handle.h
  src/devices/cuda/cuda_handle.cc
  src/devices/cuda/cuda_handle.h
  src/devices/cuda/handle_pool.cc
  src/devices/cuda/handle_pool.h
  src/devices/handle.cc
  src/main.c
  src/ops/causal_softmax/cpu/causal_softmax_cpu.cc
  src/ops/causal_softmax/cpu/causal_softmax_cpu.h
  src/ops/causal_softmax/cuda/causal_softmax.cc
  src/ops/causal_softmax/cuda/causal_softmax.cu
  src/ops/causal_softmax/cuda/causal_softmax.cuh
  src/ops/causal_softmax/operator.cc
  src/ops/matmul/blas.h
  src/ops/utils.h
  src/tensor/tensor_descriptor.cc
  xmake.lua
Labels: 模块：框架, 类别：重构, 紧急！, 进度：已完成

#36 Feature: 增加构建任意stride测例的函数，修改causal softmax测试
  operatorspy/tests/causal_softmax.py
  operatorspy/utils.py
Labels: 紧急！, 模块：测试, 类别：开发

#37 Refactor swiglu cpu&cuda
  include/ops/swiglu/swiglu.h
  operatorspy/tests/swiglu.py
  src/ops/swiglu/cpu/swiglu_cpu.cc
  src/ops/swiglu/cpu/swiglu_cpu.h
  src/ops/swiglu/cuda/swiglu.cu
  src/ops/swiglu/cuda/swiglu.cuh
  src/ops/swiglu/cuda/swiglu_cuda.cc
  src/ops/swiglu/operator.cc
Labels: 类别：重构, 进度：已完成
