Repository PanZezhong1725/operators, pull requests merged in 2024-09, with the labels that each got.

#38 Refactor：寒武纪 causal softmax 算子
  operatorspy/tests/causal_softmax.py
  src/devices/bang/bang_handle.cc
  src/devices/bang/bang_handle.h
  src/devices/bang/common_bang.h
  src/ops/causal_softmax/bang/causal_softmax_bang.cc
  src/ops/causal_softmax/bang/causal_softmax_bang.h
  src/ops/causal_softmax/bang/causal_softmax_bang.mlu
  src/ops/causal_softmax/bang/causal_softmax_cnnl.cc
  src/ops/causal_softmax/bang/causal_softmax_cnnl.h
  src/ops/causal_softmax/operator.cc
  src/ops/utils.h
Labels: 模块：算子, 类别：重构, 进度：已完成

#43 Causal Softmax计算增加set device
  operatorspy/tests/causal_softmax.py
  operatorspy/utils.py
  src/devices/cuda/cuda_handle.cc
  src/ops/causal_softmax/cuda/causal_softmax.cc
  src/ops/causal_softmax/cuda/causal_softmax.cu
  src/ops/causal_softmax/cuda/causal_softmax.cuh
  src/ops/causal_softmax/operator.cc
Labels: 类别：BUG, 模块：算子, 紧急！, 模块：测试

#39 重构rearrange的cpu/cuda算子
  include/ops/rearrage/rearrange.h
  include/ops/rearrange/rearrange.h
  include/ops/reform/reform.h
  operatorspy/tests/rearrange.py
  operatorspy/tests/reform.py
  src/ops/rearrange/cpu/rearrange_cpu.cc
  src/ops/rearrange/cpu/rearrange_cpu.h
  src/ops/rearrange/cuda/rearrange.cc
  src/ops/rearrange/cuda/rearrange.cu
  src/ops/rearrange/cuda/rearrange.cuh
  src/ops/rearrange/operator.cc
  src/ops/reform/bang/reform_bang.h
  src/ops/reform/bang/reform_bang.mlu
  src/ops/reform/cpu/reform_cpu.cc
  src/ops/reform/cpu/reform_cpu.h
  src/ops/reform/cuda/reform.cu
  src/ops/reform/cuda/reform.cuh
  src/ops/reform/operator.cc
Labels: 模块：算子, 类别：重构, 进度：已完成

#53 Refactor matmul
  include/ops/matmul/matmul.h
  operatorspy/tests/matmul.py
  src/devices/cuda/cuda_handle.cc
  src/devices/cuda/cuda_handle.h
  src/devices/cuda/handle_pool.cc
  src/devices/cuda/handle_pool.h
  src/devices/handle.cc
  src/ops/matmul/blas.h
  src/ops/matmul/cpu/matmul_cpu.cc
  src/ops/matmul/cpu/matmul_cpu.h
  src/ops/matmul/cuda/matmul_cuda.cc
  src/ops/matmul/cuda/matmul_cuda.cu
  src/ops/matmul/cuda/matmul_cuda.h
  src/ops/matmul/operator.cc
  xmake.lua
Labels: 模块：算子, 类别：重构, 进度：已完成

#48 Refactor: 重构RoPE算子（CPU、CUDA）
  include/ops/rotary_embedding/rotary_embedding.h
  operatorspy/tests/rotary_embedding.py
  src/devices/cpu/common_cpu.cc
  src/devices/cpu/cpu_handle.cc
  src/devices/cpu/cpu_handle.h
  src/ops/rotary_embedding/cpu/rotary_embedding_cpu.cc
  src/ops/rotary_embedding/cpu/rotary_embedding_cpu.h
  src/ops/rotary_embedding/cuda/rotary_embedding.cc
  src/ops/rotary_embedding/cuda/rotary_embedding.cu
  src/ops/rotary_embedding/cuda/rotary_embedding.cuh
  src/ops/rotary_embedding/operator.cc
Labels: 模块：算子, 类别：重构, 进度：已完成

#41 refactored Add operator and fixed f16 and f32 conversion functions
  include/data_type.h
  include/ops/add/add.h
  operatorspy/tests/add.py
  src/devices/cpu/common_cpu.cc
  src/devices/cuda/common_cuda.h
  src/devices/cuda/cuda_handle.cc
  src/devices/cuda/cuda_handle.h
  src/ops/add/cpu/add_cpu.cc
  src/ops/add/cpu/add_cpu.h
  src/ops/add/cuda/add.cc
  src/ops/add/cuda/add.cu
  src/ops/add/cuda/add.cuh
  src/ops/add/operator.cc
  src/ops/utils.h
  xmake.lua
Labels: 类别：BUG, 模块：算子, 类别：重构, 进度：已完成

#65 Fixed Add to correctly handle any data size
  operatorspy/tests/add.py
  src/ops/add/cuda/add.cu
Labels: 类别：BUG, 模块：算子, 进度：已完成
