Repository PanZezhong1725/operators, pull requests merged in 2024-10, with the labels that each got.

#62 bangRearrange：重构寒武纪平台rearrange算子
  include/ops/rearrange/rearrange.h
  operatorspy/tests/rearrange.py
  src/ops/matmul/bang/matmul_cnnl.cc
  src/ops/rearrange/bang/rearrange_bang.cc
  src/ops/rearrange/bang/rearrange_bang.h
  src/ops/rearrange/bang/rearrange_bang.mlu
  src/ops/rearrange/cpu/rearrange_cpu.cc
  src/ops/rearrange/cpu/rearrange_cpu.h
  src/ops/rearrange/cuda/rearrange.cu
  src/ops/rearrange/cuda/rearrange.cuh
  src/ops/rearrange/operator.cc
  src/ops/rms_norm/operator.cc
Labels: 模块：算子, 类别：重构, 进度：已完成

#60 添加 mlp 融合算子
  include/infini_operators.h
  include/ops/mlp/mlp.h
  operatorspy/tests/mlp.py
  src/ops/matmul/operator.cc
  src/ops/mlp/operator.cc
  src/ops/utils.h
  src/tensor/tensor_descriptor.cc
Labels: 模块：算子, 进度：已完成, 类别：开发

#70 添加 attention 融合算子
  include/ops/attention/attention.h
  operatorspy/tests/attention.py
  src/ops/attention/operator.cc
  src/ops/rearrange/cuda/rearrange.cuh
  src/ops/utils.h
Labels: 模块：算子, 进度：已完成, 类别：开发

#73 cnnl_matmul：修复cnnl计算matmul
  src/ops/matmul/bang/matmul_cnnl.cc
  src/ops/matmul/bang/matmul_cnnl.h
  src/ops/matmul/operator.cc
  src/ops/utils.h
Labels: 模块：算子, 进度：已完成, 类别：开发

#75 fix: 创建tensor descriptor时使用const形状和步长
  include/tensor/tensor_descriptor.h
  src/tensor/tensor_descriptor.cc
Labels: 类别：BUG, 模块：框架

#82 randomSample：增加topp和topk为0的特殊处理
  operatorspy/tests/random_sample.py
  src/ops/random_sample/bang/random_sample_bang.mlu
  src/ops/random_sample/cpu/random_sample.cc
  src/ops/random_sample/cuda/random_sample.cu
Labels: 模块：算子, 进度：已完成, 类别：优化

#83 Ascend matmul
  operatorspy/tests/matmul.py
  src/ops/matmul/ascend/matmul_aclnn.cc
  src/ops/matmul/ascend/matmul_aclnn.h
  src/ops/matmul/operator.cc
Labels: 模块：算子, 类别：重构, 进度：已完成
