Repository PanZezhong1725/operators, pull requests merged in 2024-12, with the labels that each got.

#126 调整算子库编译安装流程
  .github/workflows/main.yaml
  README.md
  xmake.lua
Labels: 文档更新, 模块：框架, 类别：重构, 进度：已完成

#127 add ascend random sample
  operatorspy/tests/random_sample.py
  src/devices/ascend/CMakeLists.txt
  src/devices/ascend/common_ascend.cc
  src/devices/ascend/common_ascend.h
  src/devices/ascend/tensor_aclnn.cc
  src/devices/ascend/tensor_aclnn.h
  src/ops/causal_softmax/ascend/causal_softmax_aclnn.cc
  src/ops/matmul/ascend/matmul_aclnn.cc
  src/ops/random_sample/ascend/random_sample.cc
  src/ops/random_sample/ascend/random_sample.h
  src/ops/random_sample/ascend/random_sample_aclnn.cc
  src/ops/random_sample/ascend/random_sample_aclnn.h
  src/ops/random_sample/ascend/random_sample_kernel.cpp
  src/ops/random_sample/operator.cc
  src/ops/rearrange/ascend/rearrange_aclnn.cc
  src/ops/rms_norm/ascend/rms_norm_aclnn.cc
  src/ops/swiglu/ascend/swiglu_kernel.cpp
Labels: 模块：算子, 进度：已完成, 类别：开发

#132 fix every error for cuda on windows
  src/devices/cuda/common_cuda.h
  src/devices/cuda/cuda_handle.h
  src/ops/add/cuda/add.cc
  src/ops/causal_softmax/bang/causal_softmax_bang.cc
  src/ops/causal_softmax/bang/causal_softmax_bang.h
  src/ops/causal_softmax/bang/causal_softmax_cnnl.cc
  src/ops/causal_softmax/bang/causal_softmax_cnnl.h
  src/ops/causal_softmax/cuda/causal_softmax.cc
  src/ops/causal_softmax/cuda/causal_softmax.cuh
  src/ops/conv/cuda/conv.cc
  src/ops/expand/cuda/expand.cc
  src/ops/global_avg_pool/cuda/global_avg_pool.cc
  src/ops/global_avg_pool/cuda/global_avg_pool.cuh
  src/ops/pooling/cuda/pooling.cc
  src/ops/pooling/cuda/pooling.cuh
  src/ops/random_sample/bang/random_sample_bang.cc
  src/ops/random_sample/bang/random_sample_bang.h
  src/ops/random_sample/cuda/random_sample.cuh
  src/ops/random_sample/cuda/random_sample_cuda.cc
  src/ops/rms_norm/bang/rms_norm_bang.cc
  src/ops/rms_norm/bang/rms_norm_bang.h
  src/ops/rms_norm/cuda/rms_norm.cc
  src/ops/rms_norm/cuda/rms_norm.cuh
  src/ops/rotary_embedding/cuda/rotary_embedding.cc
  src/ops/rotary_embedding/cuda/rotary_embedding.cuh
  xmake.lua
Labels: 模块：框架, 进度：已完成

#134 fix(cpu): 为 rearrange 支持 ndim == 1
  src/ops/rearrange/cpu/rearrange_cpu.cc
  src/ops/rearrange/cpu/rearrange_cpu.h
Labels: 进度：已完成, 类别：优化

#135 fix: 改正整数类型的问题，重写 nv rearrange
  src/ops/causal_softmax/bang/causal_softmax_bang.h
  src/ops/causal_softmax/bang/causal_softmax_bang.mlu
  src/ops/causal_softmax/bang/causal_softmax_cnnl.cc
  src/ops/causal_softmax/bang/causal_softmax_cnnl.h
  src/ops/causal_softmax/cuda/causal_softmax.cc
  src/ops/causal_softmax/cuda/causal_softmax.cu
  src/ops/causal_softmax/cuda/causal_softmax.cuh
  src/ops/matmul/ascend/matmul_aclnn.cc
  src/ops/random_sample/bang/random_sample_bang.h
  src/ops/random_sample/bang/random_sample_bang.mlu
  src/ops/rearrange/cuda/rearrange.cc
  src/ops/rearrange/cuda/rearrange.cu
  src/ops/rearrange/cuda/rearrange.cuh
  src/ops/rms_norm/bang/rms_norm_bang.cc
  src/ops/rms_norm/bang/rms_norm_bang.h
  src/ops/rms_norm/bang/rms_norm_bang.mlu
  src/ops/rms_norm/cuda/rms_norm.cu
  src/ops/rms_norm/cuda/rms_norm.cuh
  src/ops/rotary_embedding/cuda/rotary_embedding.cu
  src/ops/rotary_embedding/cuda/rotary_embedding.cuh
Labels: 类别：BUG, 模块：算子, 进度：已完成
