Repository PanZezhong1725/operators, pull requests merged in 2024-11, with the labels that each got.

#84 Ascend rearrange
  operatorspy/tests/rearrange.py
  src/ops/rearrange/ascend/rearrange_aclnn.cc
  src/ops/rearrange/ascend/rearrange_aclnn.h
  src/ops/rearrange/operator.cc
Labels: 模块：算子, 进度：已完成, 类别：开发

#78 bangRMS
  include/ops/rms_norm/rms_norm.h
  src/ops/rms_norm/bang/rms_norm_bang.cc
  src/ops/rms_norm/bang/rms_norm_bang.h
  src/ops/rms_norm/bang/rms_norm_bang.mlu
  src/ops/rms_norm/bang/rms_norm_cnnl.cc
  src/ops/rms_norm/bang/rms_norm_cnnl.h
  src/ops/rms_norm/cpu/rms_norm_cpu.cc
  src/ops/rms_norm/cpu/rms_norm_cpu.h
  src/ops/rms_norm/cuda/rms_norm.cu
  src/ops/rms_norm/cuda/rms_norm.cuh
  src/ops/rms_norm/operator.cc
Labels: 模块：算子, 类别：重构, 进度：已完成

#85 Ascend rms norm
  operatorspy/tests/rms_norm.py
  src/ops/rms_norm/ascend/rms_norm_aclnn.cc
  src/ops/rms_norm/ascend/rms_norm_aclnn.h
  src/ops/rms_norm/operator.cc
Labels: 类别：重构, 进度：已完成

#96 Ascend matmul
  src/ops/matmul/ascend/matmul_aclnn.cc
  src/ops/matmul/ascend/matmul_aclnn.h
Labels: 类别：重构, 进度：已完成

#97 Ascend rearrange
  src/ops/rearrange/ascend/rearrange_aclnn.cc
  src/ops/rearrange/ascend/rearrange_aclnn.h
Labels: 类别：重构, 进度：已完成

#99 Ascend softmax
  src/ops/causal_softmax/ascend/causal_softmax_aclnn.cc
  src/ops/causal_softmax/ascend/causal_softmax_aclnn.h
Labels: 模块：算子, 类别：重构, 进度：已完成

#61 Add conv
  include/infini_operators.h
  include/ops/conv/conv.h
  operatorspy/tests/conv.py
  src/devices/cuda/cuda_handle.cc
  src/devices/cuda/cuda_handle.h
  src/ops/conv/cpu/conv_cpu.cc
  src/ops/conv/cpu/conv_cpu.h
  src/ops/conv/cuda/conv.cc
  src/ops/conv/cuda/conv.cu
  src/ops/conv/cuda/conv.cuh
  src/ops/conv/operator.cc
Labels: 模块：算子, 进度：已完成, 类别：开发

#80 bangRoPE
  operatorspy/tests/rotary_embedding.py
  src/devices/bang/handle_pool.cc
  src/devices/bang/handle_pool.h
  src/ops/matmul/bang/matmul_cnnl.cc
  src/ops/rotary_embedding/bang/rotary_embedding_bang.cc
  src/ops/rotary_embedding/bang/rotary_embedding_bang.h
  src/ops/rotary_embedding/bang/rotary_embedding_bang.mlu
  src/ops/rotary_embedding/bang/rotary_embedding_cnnl.cc
  src/ops/rotary_embedding/bang/rotary_embedding_cnnl.h
  src/ops/rotary_embedding/operator.cc
  src/ops/swiglu/bang/swiglu_cnnl.cc
  src/ops/swiglu/bang/swiglu_cnnl.h
  src/ops/swiglu/operator.cc
Labels: 模块：算子, 类别：重构, 进度：已完成

#93 Add GEMM & Expand
  include/infini_operators.h
  include/ops/expand/expand.h
  include/ops/gemm/gemm.h
  operatorspy/tests/expand.py
  operatorspy/tests/gemm.py
  operatorspy/tests/matmul.py
  src/devices/cpu/common_cpu.cc
  src/devices/cpu/common_cpu.h
  src/devices/cuda/common_cuda.h
  src/ops/add/cuda/add.cc
  src/ops/add/cuda/add.cu
  src/ops/expand/cpu/expand_cpu.cc
  src/ops/expand/cpu/expand_cpu.h
  src/ops/expand/cuda/expand.cc
  src/ops/expand/cuda/expand.cu
  src/ops/expand/cuda/expand.cuh
  src/ops/expand/operator.cc
  src/ops/gemm/operator.cc
  src/ops/matmul/cpu/matmul_cpu.cc
  src/ops/matmul/cpu/matmul_cpu.h
  src/ops/matmul/cuda/matmul_cuda.cc
  src/ops/matmul/cuda/matmul_cuda.cu
  src/ops/matmul/cuda/matmul_cuda.h
  src/ops/utils.h
Labels: 模块：算子, 进度：已完成, 类别：开发

#89 Add Global Average Pool
  include/infini_operators.h
  include/ops/global_avg_pool/global_avg_pool.h
  operatorspy/tests/global_avg_pool.py
  src/ops/global_avg_pool/cpu/global_avg_pool_cpu.cc
  src/ops/global_avg_pool/cpu/global_avg_pool_cpu.h
  src/ops/global_avg_pool/cuda/global_avg_pool.cc
  src/ops/global_avg_pool/cuda/global_avg_pool.cu
  src/ops/global_avg_pool/cuda/global_avg_pool.cuh
  src/ops/global_avg_pool/operator.cc
Labels: 模块：算子, 进度：已完成, 类别：开发

#90 Ascend Rope & Swiglu
  .gitignore
  operatorspy/tests/rotary_embedding.py
  operatorspy/tests/swiglu.py
  src/devices/ascend/CMakeLists.txt
  src/devices/ascend/Makefile
  src/ops/rotary_embedding/ascend/rotary_embedding.cc
  src/ops/rotary_embedding/ascend/rotary_embedding.h
  src/ops/rotary_embedding/ascend/rotary_embedding_kernel.cpp
  src/ops/rotary_embedding/operator.cc
  src/ops/swiglu/ascend/swiglu.cc
  src/ops/swiglu/ascend/swiglu.h
  src/ops/swiglu/ascend/swiglu_kernel.cpp
  src/ops/swiglu/operator.cc
  xmake.lua
Labels: 模块：算子, 进度：已完成, 类别：开发

#107 refactor: 添加install项目功能
  .github/workflows/main.yaml
  operatorspy/liboperators.py
  xmake.lua
Labels: 模块：框架, 类别：重构, 紧急！

#108 Ascend matmul fix
  operatorspy/tests/matmul.py
  src/devices/ascend/tensor_aclnn.cc
  src/devices/ascend/tensor_aclnn.h
  src/ops/matmul/ascend/matmul_aclnn.cc
Labels: 类别：BUG, 紧急！, 进度：已完成

#109 fix matmul test
  operatorspy/tests/matmul.py
Labels: 类别：BUG, 紧急！, 进度：已完成

#112 fix cpu llama 推理端到端精度
  src/devices/cpu/common_cpu.cc
  src/ops/matmul/cpu/matmul_cpu.cc
Labels: 类别：BUG, 模块：算子, 进度：已完成

#113 fix: 华为matmul支持batch
  operatorspy/tests/matmul.py
  src/devices/ascend/tensor_aclnn.cc
  src/devices/ascend/tensor_aclnn.h
  src/ops/causal_softmax/ascend/causal_softmax_aclnn.cc
  src/ops/matmul/ascend/matmul_aclnn.cc
  src/ops/matmul/ascend/matmul_aclnn.h
  src/ops/rms_norm/ascend/rms_norm_aclnn.cc
Labels: 类别：BUG, 模块：算子, 紧急！, 进度：已完成

#114 fix: 修改昇腾infer storage shape和rearrange
  operatorspy/tests/rearrange.py
  src/devices/ascend/tensor_aclnn.cc
Labels: 类别：BUG, 模块：算子, 紧急！, 进度：已完成

#117 fix: 昇腾infer storage shape按1D数组
  src/devices/ascend/tensor_aclnn.cc
Labels: 类别：BUG, 模块：算子, 紧急！, 进度：已完成

#118 Hack ascend random sample
  operatorspy/tests/random_sample.py
  src/devices/ascend/tensor_aclnn.cc
  src/ops/random_sample/ascend/random_sample_aclnn.cc
  src/ops/random_sample/ascend/random_sample_aclnn.h
  src/ops/random_sample/operator.cc
Labels: 模块：算子, 紧急！, 进度：已完成

#121 临时修改：将华为rearrange准备工作全部移至计算内
  operatorspy/tests/rearrange.py
  src/ops/rearrange/ascend/rearrange_aclnn.cc
Labels: 类别：BUG, 模块：算子, 紧急！, 进度：已完成

#120 完善错误处理宏，打印报错代码所在文件及行数等具体信息
  operatorspy/tests/add.py
  operatorspy/tests/avg_pool.py
  operatorspy/tests/conv.py
  operatorspy/tests/expand.py
  operatorspy/tests/gemm.py
  operatorspy/tests/global_avg_pool.py
  operatorspy/tests/matmul.py
  operatorspy/tests/max_pool.py
  operatorspy/tests/rearrange.py
  operatorspy/tests/relu.py
  operatorspy/tests/swiglu.py
  src/devices/cuda/common_cuda.h
  src/ops/utils.h
Labels: 模块：框架, 类别：重构, 进度：已完成
