Repository PanZezhong1725/operators, pull requests merged in 2025-01, with the labels that each got.

#139 rope_debug：解决寒武纪不支持64计算的问题
  operatorspy/tests/rotary_embedding.py
  src/ops/rotary_embedding/bang/rotary_embedding_bang.mlu
Labels: 类别：BUG, 模块：算子, 进度：已完成

#142 Fix Input Copy Issues
  src/ops/add/cpu/add_cpu.cc
  src/ops/conv/cpu/conv_cpu.cc
  src/ops/pooling/cpu/pooling_cpu.cc
Labels: 类别：BUG, 紧急！, 进度：已完成

#143 python 测试中添加 TensorDescriptor 的 invalidate 接口，禁止 kernel 直接使用外部传入的形状信息指针。
  operatorspy/liboperators.py
  operatorspy/tests/add.py
  operatorspy/tests/attention.py
  operatorspy/tests/avg_pool.py
  operatorspy/tests/causal_softmax.py
  operatorspy/tests/conv.py
  operatorspy/tests/expand.py
  operatorspy/tests/gemm.py
  operatorspy/tests/global_avg_pool.py
  operatorspy/tests/matmul.py
  operatorspy/tests/max_pool.py
  operatorspy/tests/mlp.py
  operatorspy/tests/random_sample.py
  operatorspy/tests/rearrange.py
  operatorspy/tests/relu.py
  operatorspy/tests/rms_norm.py
  operatorspy/tests/rotary_embedding.py
  operatorspy/tests/swiglu.py
Labels: 类别：BUG, 紧急！, 进度：已完成, 模块：测试
